kernel_tar: handle VERSION symlinks in install script

diff --git a/src/kernel_tar b/src/kernel_tar
--- a/src/kernel_tar
+++ b/src/kernel_tar
@@ -88,20 +88,56 @@ tmpdir=`mktemp -dt \`basename $0\`-XXXX`
 
 # create the installer script
 #
-# FIXME: should check for VERSION symlink, remove what it points to if
-#        detected.
-#
 # FIXME: why do we tar FOO to stdout, pipe that into tar to install?  was it
 #        just to avoid having to retest something else when i split
 #        extracenator into a seperate script?  We could do 'cp -a' or something
 #        similar instead... right?
 #
 cat > $tmpdir/installer <<EOF
+# figure out VERSION, which might be a stable .y version w/ a symlink
+for x in FOO/lib/modules/*; do
+    if [ -h $x ]; then
+        VERSION=$(readlink $x)
+        VERSION_NAME=$(basename $x)
+        break
+    else
+        VERSION=$(basename $x)
+    fi
+done
+
+if [ -z "$VERSION" ]; then
+    echo "ERROR: can't detect VERSION; malformed installer"
+   exit 1
+fi
+
+echo VERSION: $VERSION
+echo VERSION_NAME: $VERSION_NAME
+
 echo -n "removing preexisting modules in /lib/modules/$VERSION... "
 rm -rf /lib/modules/$VERSION && echo DONE || { echo FAIL; exit 1; }
 
+if [ -n "$VERSION_NAME" ]; then
+    if [ -h /lib/modules/$VERSION_NAME; then
+        old_one=$(readlink /lib/modules/$VERSION_NAME)
+        echo -n "following $VERSION_NAME symlink to remove modules in $old_one... "
+        rm -rf /lib/modules/$old_ones && echo DONE || { echo FAIL; exit 1; }
+        echo -n "removing $VERSION_NAME symlink... "
+        rm /lib/modules/$VERSION_NAME" && echo DONE || { echo FAIL; exit 1; }
+    fi
+fi
+
 echo -n "removing preexisting headers in /usr/src/linux-headers-$VERSION... "
 rm -rf /usr/src/linux-headers-$VERSION && echo DONE || { echo FAIL; exit 1; }
+
+if [ -n "$VERSION_NAME" ]; then
+    if [ -h /usr/src/linux-headers-$VERSION_NAME; then
+        old_one=$(readlink /usr/src/linux-headers-$VERSION_NAME)
+        echo -n "following $VERSION_NAME symlink to remove headers in $old_one... "
+        rm -rf /usr/src/linux-headers-$old_ones && echo DONE || { echo FAIL; exit 1; }
+        echo -n "removing $VERSION_NAME symlink... "
+        rm /usr/src/linux-headers-$VERSION_NAME" && echo DONE || { echo FAIL; exit 1; }
+    fi
+fi
 
 echo -n "extracting archive... "
 (tar -C FOO -c . | tar -x --no-same-owner --no-same-permissions -C /) && echo DONE || { echo FAIL; exit 1; }
