microcodenator: finished initial implementation

diff --git a/src/microcodenator b/src/microcodenator
--- a/src/microcodenator
+++ b/src/microcodenator
@@ -72,46 +72,92 @@ while true; do
             ;;
     esac
 done
-filename=$(realpath $1)
 
 # check for required options
-if [ -z "$filename" ]; then
+if [ -z "$1" ]; then
     usage "IMGNAME required"
     exit 1
 fi
+filename=$(realpath $1)
 
 decho filename: $filename
 decho verbose: $verbose
-exit 0
+
+if [ -n "$verbose" ]; then
+    cp="cp -v"
+    cpio="cpio --verbose"
+    mkdir="mkdir -v"
+else
+    cp="cp"
+    cpio="cpio"
+    mkdir="mkdir"
+fi
 
 tmpdir=$(mktemp -dt $(basename $0)-XXXX)
 decho tmpdir: $tmpdir
-
 cd $tmpdir
 
-# FIXME: now what...  how do we detect which microcode files to include?  as
-#        usual, LFS to the rescue:
+# NOTE: How do we detect which microcode files to include?  as usual, LFS to
+#       the rescue:
 #
-#        http://www.linuxfromscratch.org/blfs/view/svn/postlfs/firmware.html
+#       http://www.linuxfromscratch.org/blfs/view/svn/postlfs/firmware.html
 #
 
 # look at /proc/cpuinfo cpu family, model, and stepping (all in decimal but
 # needed in hex)
+eval $(cat /proc/cpuinfo | awk '{if ($1=="processor" && $3==1) exit; \
+    if ($0~"^vendor_id[[:space:]]*:") printf "vendor_id=%s\n", $NF; \
+    if ($0~"^cpu family[[:space:]]*:") printf "cpu_family=%s\n", $NF; \
+    if ($0~"^model[[:space:]]*:") printf "cpu_model=%s\n", $NF; \
+    if ($0~"^stepping[[:space:]]*:") printf "cpu_stepping=%s\n", $NF; \
+    }')
+cpu_family=$(printf "%x" $cpu_family)
+cpu_model=$(printf "%x" $cpu_model)
+cpu_stepping=$(printf "%x" $cpu_stepping)
+decho vendor_id: $vendor_id
+decho cpu_family: $cpu_family
+decho cpu_model: $cpu_model
+decho cpu_stepping: $cpu_stepping
 
-# Intel - XX-YY-ZZ is family, model, and stepping all converted into hex.
-#
-# cp subproject/intel-ucode/intel-ucode/XX-YY-ZZ $tmpdir/kernel/x86/microcode/GenuineIntel.bin
+UCODEBASEDIR=/lib/firmware
+DESTDIR=$tmpdir/kernel/x86/microcode
+$mkdir -p $DESTDIR
+case $vendor_id in
+    GenuineIntel)
+        # Intel - XX-YY-ZZ is family, model, and stepping all converted into
+        # hex.
+        UCODEDIR=$UCODEBASEDIR/intel-ucode
+        decho UCODEDIR: $UCODEDIR
+        UCODE=$UCODEDIR/$cpu_family-$cpu_model-$cpu_stepping
+        decho UCODE: $UCODE
+        if [ -f $UCODE ]; then
+            $cp -a $UCODE $DESTDIR/GenuineIntel.bin
+        fi
+        ;;
+    AuthenticAMD)
+        # AMD - just uses family, again in hex.  Families 10h to 14h (16 to 20)
+        # are in microcode_amd.bin. Families 15h, 16h and 17h have their own
+        # containers.
+        UCODEDIR=$UCODEBASEDIR/amd-ucode
+        decho UCODEDIR: $UCODEDIR
+        case $cpu_family in
+            10|11|12|13|14)
+                UCODE=$UCODEDIR/microcode_amd.bin
+                ;;
+            *)
+                UCODE=$UCODEDIR/microcode_amd_fam${cpu_family}h.bin
+                ;;
+        esac
+        decho UCODE: $UCODE
+        if [ -f $UCODE ]; then
+            $cp -a $UCODE $DESTDIR/AuthenticAMD.bin
+        fi
+        ;;
+    *)
+        echo "ERROR: Unsupported CPU Vendor ID: $vendor_id"
+        exit 1
+esac
 
-# AMD - just uses family, again in hex.  Families 10h to 14h (16 to 20) are in
-# microcode_amd.bin. Families 15h, 16h and 17h have their own containers.
-#
-# cp subproject/linux-firmware/amd-ucode/MYCONTAINER $tmpdir/kernel/x86/microcode/AuthenticAMD.bin
-
-if [ -n "$verbose" ]; then
-    cpio="cpio --verbose"
-else
-    cpio="cpio"
-fi
 find . | $cpio -o -H newc > $filename
 
 rm -rf $tmpdir
